# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
minversion = 3.15
envlist = ruff, pylint, mypy, pep257, py{,py}3{9,10,11,12,13,14,15},py31{3,4,5}t, readme, doc8, docs
skip_missing_interpreters = True

[testenv]
recreate = True
usedevelop = True
passenv =
  http_proxy
  HTTP_PROXY
  https_proxy
  HTTPS_PROXY
  no_proxy
  NO_PROXY
setev = PYTHONDONTWRITEBYTECODE=1
deps =
  sphinx
  -r{toxinidir}/pytest_requirements.txt
  pytest-html

commands =
  pip freeze
  py.test --self-contained-html --html=report.html

[testenv:py{,py}3{8,9,10,11,12,13,14,15}{,t}]
depends = pylint,mypy,ruff,ruff-format,pep257,bandit

[testenv:venv]
commands = {posargs:}

[testenv:ruff]
skip_install = true
depends = ruff-format
deps = ruff>=0.14.6
commands = ruff check .

[testenv:ruff-format]
skip_install = true
deps = ruff>=0.14.6
commands = ruff format --check .

[testenv:pep257]
skip_install = true
depends = ruff-format
deps =
  pydocstyle[toml]
commands = pydocstyle -v logwrap

[testenv:doc8]
skip_install = true
deps =
  doc8
  Pygments
commands = doc8 README.rst doc/source

[testenv:install]
deps =
commands = pip install ./ -vvv -U

[testenv:pylint]
depends = ruff,ruff-format,pep257,bandit
deps =
  pylint>=3.0.0
commands =
  pylint logwrap

[testenv:docs]
depends = doc8,readme
deps =
  sphinx
commands = sphinx-build doc/source/ doc/build

[testenv:readme]
skip_install = true
deps =
  twine
  build
commands =
  python -m build -s
  twine check {toxinidir}/dist/*

[testenv:bandit]
deps = bandit
commands = bandit -r logwrap

[testenv:dep-graph]
deps =
  .
  pipdeptree
commands = pipdeptree

[testenv:mypy]
depends = ruff,ruff-format,pep257,bandit
deps =
  mypy>=2.0
  lxml
  rich
commands =
  mypy --strict --show-error-codes --xslt-html-report mypy_report -p logwrap
